---
name: 'Robot Reporter'
description: 'Parses robot framework test reports and outputs the results in commit that triggered the tests'
author: 'joseajunior'
inputs:
  report_path:
    description: |
      Path to the report files.
      The default value is "reports"
    required: false
    default: "reports"
  gh_access_token:
    description: |
      Token to access the GitHub API.
      This is only needed if you want to post the report to the pull request that triggered the tests.
    required: false
    default: "none"
  pr_number:
    description: |
      Pull Request number.
      This is only needed if you want to post the report to the pull request that triggered the tests.
    required: false
    default: "${{ github.event.pull_request.number }}"
  only_summary:
    description: |
      Only output report to GitHub Actions Summary.
      Default is false.
    required: false
    default: false
  include_passed:
    description: |
      Include passed tests in the report.
      Default is false.
    required: false
    default: false
  webhook_url:
    description: |
      Google Chat webhook URL.
      This is only needed if you want to post the report to a Google Chat room.
    required: false
    default: false
  report_title:
    description: |
      Report Title for Google Chat report.
      This is only needed if you want to post the report to a Google Chat room.
    required: false
    default: "Robot Framework Report"
  report_link:
    description: |
      Report Link for GitHub Action.
      This is only needed if you want to post the report to a Google Chat room.
    required: false
    default: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  only_on_failure:
    description: |
      Only send the Google Chat report if there are failed tests.
      Default is false.
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        export OWNER="$(echo "${{ github.repository }}" | awk -F / '{print $1}' | sed -e "s/:refs//")"
        export REPO="$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        echo "REPOSITORY_OWNER=$OWNER" >> $GITHUB_ENV
        echo "REPOSITORY_NAME=$REPO" >> $GITHUB_ENV
        pip install robotframework requests

    - shell: bash
      run: |
        python ${{ github.action_path }}/report.py -r ${{ inputs.report_path }} -p ${{ inputs.include_passed }}
        echo "${HAS_FAILS}"
        echo "$HAS_FAILS"
        echo "${{ env.HAS_FAILS }}"

    - shell: bash
      run: |
        cat report.md >> $GITHUB_STEP_SUMMARY

    - shell: bash
      if: ${{ inputs.only_summary == 'false' }}
      env:
        GITHUB_TOKEN: ${{ inputs.gh_access_token || 'none' }}
        PR_NUMBER: ${{ inputs.pr_number || 'none' }}
      run: |
        python ${{ github.action_path }}/post.py

    - shell: bash
      if: ${{ inputs.webhook_url != 'false' }}
      env:
        HAS_FAILS: ${{ env.HAS_FAILS }}
      run: |
        python ${{ github.action_path }}/google_chat.py -s statistics.json -t "${{ inputs.report_title }}" -l "${{ inputs.report_link }}" -of "${{ inputs.only_on_failure }}" "${{ inputs.webhook_url }}"
