---
name: 'Page Uploader'
description: 'Uploads the Robot Framework test reports to GitHub Pages'
author: 'joseajunior'
inputs:
  pages_branch:
    description: |
      Branch where the pages will be uploaded.
      Default is gh-pages.
    required: false
    default: "gh-pages"
  report_path:
    description: |
      Path to the report files.
    required: true
  environment:
    description: |
      Environment where the tests were executed.
    required: true
  run_number:
    description: |
      Run number of the workflow.
      Default is the current run number.
    required: false
    default: "${{ github.run_number }}"
  gh_pages_url:
    description: |
      URL of the GitHub Pages.
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add ${{ inputs.report_path }}/*.html
        git add ${{ inputs.report_path }}/*.png && exit 0
        git commit -m "Add Robot Test Reports #${{ inputs.run_number }} On ${{ inputs.environment }} Environment"
        git push origin ${{ inputs.pages_branch }}

    - shell: bash
      run: |
        echo "### [Report link](${{ inputs.gh_pages_url }}/${{ inputs.report_path }}/report.html)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### [Logs link](${{ inputs.gh_pages_url }}/${{ inputs.report_path }}/log.html)" >> $GITHUB_STEP_SUMMARY
