---
name: 'Page Uploader'
description: 'Uploads the Robot Framework test reports to GitHub Pages'
author: 'joseajunior'
inputs:
  pages_branch:
    description: |
      Branch where the pages will be uploaded.
      Default is gh-pages.
    required: false
    default: "gh-pages"
  report_path:
    description: |
      Path to the report files.
    required: true
  environment:
    description: |
      Environment where the tests were executed.
    required: true
  run_number:
    description: |
      Run number of the workflow.
      Default is the current run number.
    required: false
    default: "${{ github.run_number }}"
  gh_token:
    description: |
      GitHub token to access the API.
    required: true
  gh_repository:
    description: |
      GitHub repository where the pages will be uploaded.
      Default is the current repository.
    required: false
    default: "${{ github.repository }}"

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - shell: bash
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f ${{ inputs.report_path }}/*.html
        git add -f ${{ inputs.report_path }}/*.png || true
        git commit -m "Add Robot Test Reports #${{ inputs.run_number }} On ${{ inputs.environment }} Environment"
        git push origin ${{ inputs.pages_branch }}

    - shell: bash
      run: |
        GH_URL=`curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.gh_token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ inputs.gh_repository }}/pages | jq -r '.html_url' `
        echo "GitHub Pages URL: $GH_URL"
        echo "### [Report link]($GH_URL${{ inputs.report_path }}/report.html)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### [Logs link]($GH_URL${{ inputs.report_path }}/log.html)" >> $GITHUB_STEP_SUMMARY
