---
name: Checking GitHub Pages URL

on:
  workflow_dispatch:

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run:
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Test Curl
        run: |
          GH_URL=`curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/pages | jq -r '.html_url' `
          echo "GitHub Pages URL: $GH_URL"
